version: "3.9"  
services:
  web:
    image: nginx:1.21.1-alpine
    volumes:
      - ./templates:/etc/nginx/templates
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
   
   
  
